name: 'Auto Squash Merge'
description: 'develop -> main auto squash and merge'
inputs:
  source-branch:
    description: 'Source branch'
    default: 'develop'
  target-branch:
    description: 'Target branch'
    default: 'main'
runs:
  using: 'composite'
  steps:
    - name: Setup git config
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Check source branch exists
      id: branch-check
      shell: bash
      run: |
        if ! git ls-remote --exit-code --heads origin ${{ inputs.source-branch }} > /dev/null 2>&1; then
          echo "skip=true" >> $GITHUB_OUTPUT
        fi
        exit 0

    - name: Check if merge needed
      if: steps.branch-check.outputs.skip != 'true'
      id: check
      shell: bash
      run: |
        git fetch origin
        if git merge-base --is-ancestor origin/${{ inputs.target-branch }} origin/${{ inputs.source-branch }}; then
          echo "merge_needed=true" >> $GITHUB_OUTPUT
        fi
        exit 0

    - name: Generate smart commit message
      if: steps.check.outputs.merge_needed == 'true'
      id: message
      shell: bash
      run: |
        commits=$(git log origin/${{ inputs.target-branch }}..origin/${{ inputs.source-branch }} --oneline --pretty=format:"%s")
        filtered=""
        seen_messages=()
        echo "$commits" | while IFS= read -r line; do
          msg=$(echo "$line" | cut -d' ' -f2-)
          if [[ "$msg" =~ ^typo$|^.?[Ff]ix:?\ +[Tt]ypo$ ]]; then
          if [[ " ${seen_messages[*]} " =~ " $msg " ]]; then
            count=$(echo "$filtered" | grep -c "^$msg" || echo "0")
            filtered=$(echo "$filtered" | sed "s/^$msg (x$count)$/$msg (x$((count+1)))/")
          else
            seen_messages+=("$msg")
            filtered+="$msg"$'\n'
          fi
        done

        echo "$filtered" > /tmp/filtered_commits.txt
        if [ ! -s /tmp/filtered_commits.txt ]; then
          echo "msg=Auto squash merge (no significant changes)" >> $GITHUB_OUTPUT
        elif [ $(wc -l < /tmp/filtered_commits.txt) -eq 1 ]; then
          echo "msg=$(head -1 /tmp/filtered_commits.txt)" >> $GITHUB_OUTPUT
        else
          summary=$(head -3 /tmp/filtered_commits.txt | paste -sd '\n' -)
          echo "msg=$summary" >> $GITHUB_OUTPUT
        fi

    - name: Squash merge
      if: steps.check.outputs.merge_needed == 'true'
      shell: bash
      run: |
        git checkout ${{ inputs.target-branch }}
        git merge origin/${{ inputs.source-branch }} --squash || exit 1
        git commit -m "${{ steps.message.outputs.msg }}"
        git push origin ${{ inputs.target-branch }}

