name: 'Auto Squash Merge'
description: 'develop -> main auto squash and merge'
inputs:
  source-branch:
    description: 'Source branch'
    default: 'develop'
  target-branch:
    description: 'Target branch'
    default: 'main'
runs:
  using: 'composite'
  steps:
    - name: Setup git config
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Check source branch exists
      id: branch-check
      shell: bash
      run: |
        if ! git ls-remote --exit-code --heads origin ${{ inputs.source-branch }} > /dev/null 2>&1; then
          echo "skip=true" >> $GITHUB_OUTPUT
        fi
        exit 0

    - name: Check if merge needed
      if: steps.branch-check.outputs.skip != 'true'
      id: check
      shell: bash
      run: |
        git fetch origin
        if git merge-base --is-ancestor origin/${{ inputs.target-branch }} origin/${{ inputs.source-branch }}; then
          echo "merge_needed=true" >> $GITHUB_OUTPUT
        fi
        exit 0

    - name: Generate smart commit message
      id: message
      shell: bash
      run: |
        commits=$(git log origin/${{ inputs.target-branch }}..origin/${{ inputs.source-branch }} --oneline --pretty=format:"%s")

        filtered=""
        seen=()

        while IFS= read -r commit; do
          msg="${commit#* }"
          # skip too little commit messages
          if [[ "$msg" =~ ^typo$|^.?[Ff]ix:?\ +[Tt]ypo$ ]]; then
            continue
          fi

          # uniq
          duplicate=false
          for prev in "${seen[@]}"; do
            if [[ "$prev" == "$msg" ]]; then
              duplicate=true
              break
            fi
          done << (echo "$commits")

          if [[ "$duplicate" == false ]]; then
            seen+=("$msg")
            filtered+="$msg"$'\n'
          fi
        done

        # create the message
        if [ -z "$filtered" ]; then
          latest_commit=$(git log -1 origin/${{ inputs.source-branch }} --pretty=format:"%s")
          echo "msg<<COMMIT" >> $GITHUB_OUTPUT
          echo "$latest_commit" >> $GITHUB_OUTPUT
          echo "COMMIT" >> $GITHUB_OUTPUT
        else
          echo "msg<<COMMITS" >> $GITHUB_OUTPUT
          echo "$filtered" >> $GITHUB_OUTPUT
          echo "COMMITS" >> $GITHUB_OUTPUT
        fi

    - name: Squash merge
      if: steps.check.outputs.merge_needed == 'true'
      shell: bash
      run: |
        git checkout ${{ inputs.target-branch }}
        git merge origin/${{ inputs.source-branch }} --squash || exit 1
        git commit -m "${{ steps.message.outputs.msg }}"
        git push origin ${{ inputs.target-branch }}

